# Generated by Django 3.1 on 2020-08-16 15:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True, max_length=300, null=True)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('venue', models.TextField(blank=True, max_length=300)),
                ('venue_url', models.URLField(blank=True, null=True)),
                ('code', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
