# Generated by Django 3.1 on 2020-08-16 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='code',
            new_name='image_url',
        ),
    ]
